export const dataList = [
    {
        id: 1,
        promotion: "-7%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Hà Nội",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://cdn2.vietnambooking.com/wp-content/uploads/hotel_pro/hotel_344561/f3795ba94ff3d49597049bf41dd0a419.jpg",
        point: "9.2",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 2,
        promotion: "-10%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Đà Nẵng",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://image.bnews.vn/MediaUpload/Org/2016/10/03/145755_intercontinental-danang-sun-peninsula-resort.jpg",
        point: "9.5",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 3,
        promotion: "-8%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Hồ Chí Minh",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "http://reviewvilla.vn/wp-content/uploads/2022/04/Hilton-Da-Nang-1.jpeg",
        point: "9.8",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 4,
        promotion: "-12%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Nha Trang",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://resortdanang.info/wp-content/uploads/2019/01/toan-canh-sheraton-resort-da-nang-1024x576.jpg",
        point: "9.1",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 5,
        promotion: "-10%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Hội An",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://q-cf.bstatic.com/images/hotel/max1024x768/173/173384842.jpg",
        point: "9.5",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 6,
        promotion: "-10%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Phú Quốc",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://cdn.nhatrangbooking.com.vn/images/uploads/02222020035050022-khach-san-florida-nha-trang.jpg",
        point: "9.6",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 7,
        promotion: "-15%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Đà Lạt",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://phuquoc.intercontinental.com/uploads/phuquoc/homepage/Sunset%20View%20from%20Resort%20%26%20Ombra%20-%2016x9.jpg",
        point: "9.7",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 8,
        promotion: "-20%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Sapa",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://cf.bstatic.com/xdata/images/hotel/max1280x900/318712637.jpg?k=ba20f9f28d3e59bb6fe9d4de4cce1468c00a12f7642874669adbdb2a23699879&o=&hp=1",
        point: "9.4",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 9,
        promotion: "-3%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Sapa",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.2",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 10,
        promotion: "-3%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Sapa",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.2",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
   
]