export const dataBlog = [
  {
    id: 1,
    imgCXG: 'https://cafebiz.cafebizcdn.vn/thumb_w/600/162123310254002176/2020/11/26/photo1606398922490-16063989227341400894245.jpg',
    title: 'Review Tiệm bánh Cối Xay Gió nơi check in hoàn hảo',
    nameDS: 'BY Đoàn Thúy',
    time: '10/05/2022',
    amountCmt: '1',
    cmt: 'Điều đầu tiên bạn cảm nhận được khi đến Tiệm bánh Cối Xay Gió này có lẽ là chất retro và ... ',
  },
  {
    id: 2,
    imgCXG: 'https://www.vietnambooking.com/wp-content/uploads/2020/07/hon-kho-quy-nhon-1.jpg',
    title: 'Ngắm Quy Nhơn, Phú Yên cực chill từ gia đình dễ thương',
    nameDS: 'BY Văn Việt',
    time: '12/04/2022',
    amountCmt: '1',
    cmt: 'Trong một chuyến du lịch cùng gia đình đến Quy Nhơn và Phú Yên kéo dài 12 ngày, anh Trương Mạnh Huy (34 tuổi, làm nghề nhiếp ảnh tại Hà Nội) đã thực hiện bộ ảnh ghi lại khoảnh khắc hạnh phúc bên gia đình nhỏ. Đặc biệt, bộ ảnh… ',
  },
  {
    id: 3,
    imgCXG: 'https://www.kynghidongduong.vn/images/product/img1/2_co-to-kynghidongduong-vn.jpg',
    title: 'Review lịch trình du lịch Cô Tô 2N1Đ chỉ 1tr8/người',
    nameDS: 'BY Lam Linh',
    time: '21/06/2022',
    amountCmt: '1',
    cmt: 'Mùa hè mà không đi biển là bạn đang chống lại mẹ thiên nhiên đấy, đi Cô Tô liền bạn nha! ',
  },
  {
    id: 4,
    imgCXG: 'https://dulichchat.com/wp-content/uploads/2020/02/du-lich-hue-thang-6-dulichchat-780x405.jpg',
    title: 'Một Huế dịu dàng và trầm mặc theo một cách rất riêng',
    nameDS: 'BY Tấn Hưng',
    time: '15/05/2022',
    amountCmt: '1',
    cmt: 'Chắc hẳn ai cũng có những nơi tự hứa nhất định sẽ phải đặt chân đến. Kiểu như “mình nhất định sẽ đi Đà Lạt, đi Hội An, đi Phú Yên…” Mình cũng vậy, và Huế là 1 trong những nơi mình luôn mong muốn được đến. Nhiều người nói… ',
  },
  {
    id: 5,
    imgCXG: 'https://3.bp.blogspot.com/-MYz47-CD_ig/Whw2P_O0m6I/AAAAAAABP8Y/piWDhHo0BA0S77PYhXh8OVPf64kezZ-6ACKgBGAs/s1600/dao-ly-son-o-dau-2.jpg',
    title: 'Du lịch Lý Sơn – nơi bạn nên ít nhất một lần đặt chân đến',
    nameDS: 'BY Thanh Phong',
    time: '10/04/2022',
    amountCmt: '1',
    cmt: 'Đến Lý Sơn để được trải nghiệm, được khám phá và được… đen da. Chuyến đi vừa rồi thực sự khiến mình mê mẩn và lưu luyến nơi này. Lần sau ghé lại Lý Sơn, mình chắc chắn sẽ dành toàn bộ thời gian cho Đảo Bé, vì Đảo Bé… ',
  },
  {
    id: 6,
    imgCXG: 'https://cdn.tgdd.vn/Files/2021/04/09/1342079/5-quan-ca-phe-song-ao-dep-nhat-khi-den-da-lat-202104092147433320.jpg',
    title: 'Review chuyến đi check in các quán cafe tại Đà Lạt',
    nameDS: 'BY XUÂN HOÀNG',
    time: '29/05/2022',
    amountCmt: '0',
    cmt: 'Điều đầu tiên bạn cảm nhận được khi đến Tiệm bánh Cối Xay Gió này có lẽ là chất retro và ... ',
  },
  {
    id: 7,
    imgCXG: 'https://thuenhadulich.vn/wp-content/uploads/2019/06/kinh-nghiem-du-lich-phu-quoc-cho-cap-doi-2019.jpg',
    title: 'Du lịch Phú Quốc cùng người thương – Thanh xuân nhất định phải một lần bạn nhé!',
    nameDS: 'BY Thành Lâm',
    time: '27/04/2022',
    amountCmt: '1',
    cmt: 'Cùng theo chân cặp đôi của cô bạn xinh đẹp Ngan Bella khám phá Phú Quốc đáng nhớ nhé. Lưu ngay bài viết Du lịch Phú Quốc cùng người thương – Thanh xuân nhất định phải một lần bạn nhé! ',
  },
]